[package]
name = "metanoid_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
metanoid_core = { path = "../metanoid_core" }
metanoid_procgen = { path = "../metanoid_procgen" }
metanoid_audio = { path = "../metanoid_audio" }
bevy = { workspace = true }
bevy_tweening = { workspace = true }
bevy_kira_audio = { workspace = true }
